# Generated by Django 3.1.4 on 2021-01-02 17:38

from django.db import migrations
import reviews.ranges


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=reviews.ranges.IntegerRangeField(default=1901),
            preserve_default=False,
        ),
    ]
